language: shell
env:
  global:
  - BUILD_NAME="UltraStar Play Companion"
  - UNITYCI_PROJECT_NAME="UltraStar Play Companion"
  
services:
- docker
  
# only run builds on pushes to the main branch
branches:
  only:
  - main

# send email notifications when the build changes from succeeding to broken
notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  - chmod +x ./tools/travis/docker_test.sh
  - chmod +x ./tools/travis/docker_build.sh
  - chmod +x ./tools/travis/build.sh
  - chmod +x ./tools/travis/before_script.sh
  - chmod +x ./tools/travis/test.sh
  - chmod +x ./tools/download-dependencies/*.sh
  - export -f travis_fold
  - (cd tools/download-dependencies/; sh download-dependencies.sh)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull $IMAGE_NAME

jobs:
  include:
  - stage: test
    script: "./tools/travis/docker_test.sh"
    env: TEST_PLATFORM=editmode IMAGE_NAME=unityci/editor:ubuntu-2020.2.1f1-linux-il2cpp-0.7.0
    addons:
      artifacts:
        s3_region: "eu-west-1"
        paths:
        - "$(pwd)/$TEST_PLATFORM-results.xml"
  - stage: test
    script: "./tools/travis/docker_test.sh"
    env: TEST_PLATFORM=playmode IMAGE_NAME=unityci/editor:ubuntu-2020.2.1f1-linux-il2cpp-0.7.0
    addons:
      artifacts:
        s3_region: "eu-west-1"
        paths:
        - "$(pwd)/$TEST_PLATFORM-results.xml"
  - stage: build
    env: BUILD_TARGET=Android IMAGE_NAME=unityci/editor:ubuntu-2020.2.1f1-android-0.7.0
    script: "./tools/travis/docker_build.sh"
    addons:
      artifacts:
        s3_region: "eu-west-1"
        paths:
        - "$(pwd)/UltraStarPlayCompanion-build.tar.gz"
